[Thu Oct 17 12:12:00 2019] [Out]: Args: ['C:/Users/quint/Documents/GitHub/QplayBubbles-Releaes/__main__.py', 'v1.5.1-pre5', 'v1_5_1_pre5', '16']
[Thu Oct 17 12:12:00 2019] [Out]: Launcher Path: C:\Users\quint\Documents
[Thu Oct 17 12:12:01 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 12:12:01 2019] [Err]:   File "C:/Users/quint/Documents/GitHub/QplayBubbles-Releaes/__main__.py", line 105, in <module>
[Thu Oct 17 12:12:01 2019] [Err]:     Main.Game(launcher_cfg)
[Thu Oct 17 12:12:01 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\Main.py", line 7, in __init__
[Thu Oct 17 12:12:01 2019] [Err]:     self.pre_initialize()
[Thu Oct 17 12:12:01 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\Main.py", line 85, in pre_initialize
[Thu Oct 17 12:12:01 2019] [Err]:     file = open("lang/%s.yaml" % config["language"])
[Thu Oct 17 12:12:01 2019] [Err]: KeyError: 'language'
