[Thu Oct 17 13:46:09 2019] [Out]: Args: ['C:/Users/quint/Documents/GitHub/QplayBubbles-Releaes/__main__.py', 'v1.5.1-pre5', 'v1_5_1_pre5', '16']
[Thu Oct 17 13:46:09 2019] [Out]: Launcher Path: C:\Users\quint\Documents
[Thu Oct 17 13:46:09 2019] [Out]: {'bubble': {'chance': 10, 'max-radius': 30, 'min-radius': 21, 'max-speed': 4.8, 'base-speed': 4.8, 'screen-gap': 100}, 'game': {'level-score': 10000, 'time-limit': 90, 'pause': False, 'resolution': '1920x1080', 'ship-radius': 15, 'ship-speed': 10, 'fullscreen': True, 'language': 'en'}, 'font': {'family': 'helvetica', 'size': -9}}
[Thu Oct 17 13:46:12 2019] [Err]: Exception in Tkinter callback
[Thu Oct 17 13:46:12 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:46:12 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
[Thu Oct 17 13:46:12 2019] [Err]:     return self.func(*args)
[Thu Oct 17 13:46:12 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 75, in <lambda>
[Thu Oct 17 13:46:12 2019] [Err]:     font=[self.font, 20 + self.f_size], command=lambda: self.title_back())
[Thu Oct 17 13:46:12 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 534, in title_back
[Thu Oct 17 13:46:12 2019] [Err]:     sleep(1)
[Thu Oct 17 13:46:12 2019] [Err]: NameError: name 'sleep' is not defined
[Thu Oct 17 13:46:14 2019] [Err]: Exception in Tkinter callback
[Thu Oct 17 13:46:14 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:46:14 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
[Thu Oct 17 13:46:14 2019] [Err]:     return self.func(*args)
[Thu Oct 17 13:46:14 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 75, in <lambda>
[Thu Oct 17 13:46:14 2019] [Err]:     font=[self.font, 20 + self.f_size], command=lambda: self.title_back())
[Thu Oct 17 13:46:14 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 534, in title_back
[Thu Oct 17 13:46:14 2019] [Err]:     sleep(1)
[Thu Oct 17 13:46:14 2019] [Err]: NameError: name 'sleep' is not defined
[Thu Oct 17 13:46:14 2019] [Err]: Exception in Tkinter callback
[Thu Oct 17 13:46:14 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:46:14 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
[Thu Oct 17 13:46:14 2019] [Err]:     return self.func(*args)
[Thu Oct 17 13:46:14 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 75, in <lambda>
[Thu Oct 17 13:46:14 2019] [Err]:     font=[self.font, 20 + self.f_size], command=lambda: self.title_back())
[Thu Oct 17 13:46:14 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 534, in title_back
[Thu Oct 17 13:46:14 2019] [Err]:     sleep(1)
[Thu Oct 17 13:46:14 2019] [Err]: NameError: name 'sleep' is not defined
[Thu Oct 17 13:46:14 2019] [Err]: Exception in Tkinter callback
[Thu Oct 17 13:46:14 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:46:14 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
[Thu Oct 17 13:46:14 2019] [Err]:     return self.func(*args)
[Thu Oct 17 13:46:14 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 75, in <lambda>
[Thu Oct 17 13:46:14 2019] [Err]:     font=[self.font, 20 + self.f_size], command=lambda: self.title_back())
[Thu Oct 17 13:46:15 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 534, in title_back
[Thu Oct 17 13:46:15 2019] [Err]:     sleep(1)
[Thu Oct 17 13:46:15 2019] [Err]: NameError: name 'sleep' is not defined
[Thu Oct 17 13:46:15 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:46:15 2019] [Err]:   File "C:/Users/quint/Documents/GitHub/QplayBubbles-Releaes/__main__.py", line 105, in <module>
[Thu Oct 17 13:46:15 2019] [Err]:     Main.Game(launcher_cfg)
[Thu Oct 17 13:46:15 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\Main.py", line 20, in __init__
[Thu Oct 17 13:46:15 2019] [Err]:     self.slotsMenu = SlotsMenu(self.start_game, self.return_title)
[Thu Oct 17 13:46:15 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\slots.py", line 249, in __init__
[Thu Oct 17 13:46:15 2019] [Err]:     self.root.update_idletasks()
[Thu Oct 17 13:46:15 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1182, in update_idletasks
[Thu Oct 17 13:46:15 2019] [Err]:     self.tk.call('update', 'idletasks')
[Thu Oct 17 13:46:15 2019] [Err]: _tkinter.TclError: can't invoke "update" command: application has been destroyed
