[Thu Oct 17 13:51:37 2019] [Out]: Args: ['C:/Users/quint/Documents/GitHub/QplayBubbles-Releaes/__main__.py', 'v1.5.1-pre5', 'v1_5_1_pre5', '16']
[Thu Oct 17 13:51:37 2019] [Out]: Launcher Path: C:\Users\quint\Documents
[Thu Oct 17 13:51:37 2019] [Out]: {'bubble': {'chance': 10, 'max-radius': 30, 'min-radius': 21, 'max-speed': 4.8, 'base-speed': 4.8, 'screen-gap': 100}, 'game': {'level-score': 10000, 'time-limit': 90, 'pause': False, 'resolution': '1920x1080', 'ship-radius': 15, 'ship-speed': 10, 'fullscreen': True, 'language': 'en'}, 'font': {'family': 'helvetica', 'size': -9}}
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-4:
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-1:
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:38 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:38 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:38 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:38 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:38 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:38 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:38 2019] [Err]: 
[Thu Oct 17 13:51:38 2019] [Err]: 
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-8:
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-5:
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:38 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:38 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:38 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:38 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-12:
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-9:
[Thu Oct 17 13:51:38 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:38 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]: 
[Thu Oct 17 13:51:38 2019] [Err]: 
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:38 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:38 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:38 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:38 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:38 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:38 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:38 2019] [Err]: 
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-13:
[Thu Oct 17 13:51:38 2019] [Err]: 
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-16:
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:38 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:38 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:38 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:38 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-20:
[Thu Oct 17 13:51:38 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:38 2019] [Err]: Exception in thread Thread-17:
[Thu Oct 17 13:51:38 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]: 
[Thu Oct 17 13:51:38 2019] [Err]: 
[Thu Oct 17 13:51:38 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:     self.run()
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:38 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-24:
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-21:
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-25:
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-28:
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:39 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-32:
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-29:
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-33:
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-36:
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:39 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-40:
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-37:
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:39 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-41:
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-44:
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:39 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-45:
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-48:
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-49:
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-52:
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-53:
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:39 2019] [Err]: Exception in thread Thread-56:
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:39 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:39 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:39 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:39 2019] [Err]:     self.run()
[Thu Oct 17 13:51:39 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:39 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]: 
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:39 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:39 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-57:
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-60:
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-64:
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-61:
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-65:
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-68:
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-72:
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-69:
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-76:
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-73:
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-77:
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-80:
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-84:
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-81:
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-85:
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-88:
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-89:
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-92:
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-96:
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:40 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:40 2019] [Err]:     self.run()
[Thu Oct 17 13:51:40 2019] [Err]: Exception in thread Thread-93:
[Thu Oct 17 13:51:40 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]: 
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:40 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:40 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:40 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:40 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-97:
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-100:
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 12[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-104:
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-101:
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-105:
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-108:
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-112:
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-109:
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-116:
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-113:
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-120:
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-117:
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-124:
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-121:
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-128:
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-125:
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-132:
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-129:
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:41 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]: 
[Thu Oct 17 13:51:41 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-136:
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:41 2019] [Err]:     self.run()
[Thu Oct 17 13:51:41 2019] [Err]: Exception in thread Thread-133:
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:41 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:41 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:41 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:41 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-137:
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-140:
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-141:
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-144:
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-145:
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-149:
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-152:
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-153:
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-156:
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-157:
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-160:
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-164:
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-161:
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-168:
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-165:
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-169:
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-172:
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:42 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-173:
[Thu Oct 17 13:51:42 2019] [Err]: Exception in thread Thread-176:
[Thu Oct 17 13:51:42 2019] [Err]:     self.run()
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:42 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:42 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:42 2019] [Err]: 
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:42 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:42 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:42 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-180:
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-177:
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-184:
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-181:
[Thu Oct 17 13:51:43 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:43 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:43 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-185:
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-188:
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-189:
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-192:
[Thu Oct 17 13:51:43 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
.py", line 129, in update
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\thr[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-196:
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-197:
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-200:
elf._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('update')
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-201:
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]: Exception in thread Thread-204:
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]: Traceback (most recent call last):
[Thu Oct 17 13:51:43 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 129, in update
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 53, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 917, in _bootstrap_inner
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.create_bubble()).start()
[Thu Oct 17 13:51:43 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Thu Oct 17 13:51:43 2019] [Err]: 
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1164, in winfo_width
[Thu Oct 17 13:51:43 2019] [Err]:     self._canvas.update()
[Thu Oct 17 13:51:43 2019] [Err]:     self.tk.call('winfo', 'width', self._w))
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 56, in <lambda>
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Documents\GitHub\QplayBubbles-Releaes\lib\title.py", line 97, in create_bubble
[Thu Oct 17 13:51:43 2019] [Err]:     self.run()
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\tkinter\__init__.py", line 1177, in update
[Thu Oct 17 13:51:43 2019] [Err]: RuntimeError: main thread is not in main loop
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:   File "C:\Users\quint\Anaconda3\lib\threading.py", line 865, in run
[Thu Oct 17 13:51:43 2019] [Err]:     x = self._root.winfo_width() + 100
[Thu Oct 17 13:51:43 2019] [Err]:     Thread(None, lambda: self.background.update()).start()
